# app/services/gemini.py
import re
import httpx
from app.core.config import settings  # or from app.core.security import settings

GEMINI_MODEL = "gemini-2.5-flash"
GEMINI_URL = f"https://generativelanguage.googleapis.com/v1beta/models/{GEMINI_MODEL}:generateContent"


def clean_generated_workflow(text: str) -> str:
    """Remove markdown decorations and extraneous headings from Gemini output."""
    text = re.sub(r"(?m)^AI Generated Output\s*$", "", text)
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)
    return text.strip()

async def generate_workflow_from_prompt(prompt: str) -> str:
    """
    Calls Gemini and returns the generated text (workflow summary).
    """
    system_instruction = (
        "You are an AI system responsible for converting a user's natural language automation request into a structured JSON specification for an AI agent workflow.\n\n"
        "CONTEXT\n\n"
        "The user is using a platform called \"OmniAgent\", where they:\n\n"
        "1. Select a domain (e.g., Corporate Operations, Education, Finance)\n"
        "2. Provide a detailed prompt describing an automation task\n\n"
        "Your job is to:\n\n"
        "* Understand the user’s intent\n"
        "* Extract structured metadata\n"
        "* Define the workflow\n"
        "* Identify required sub-agents and actions\n\n"
        "---\n\n"
        "INPUT\n\n"
        "You will receive:\n\n"
        "* domain: (string)\n"
        "* user_prompt: (string)\n\n"
        "---\n\n"
        "OUTPUT FORMAT (STRICT JSON ONLY)\n\n"
        "Return ONLY valid JSON. No explanation.\n\n"
        "{\n"
        "\"domain\": \"\",\n"
        "\"task_summary\": \"\",\n"
        "\"intent_type\": \"\",\n"
        "\"complexity\": \"\",\n"
        "\"required_agents\": [\n"
        "  {\n"
        "    \"agent_name\": \"\",\n"
        "    \"role\": \"\",\n"
        "    \"responsibilities\": []\n"
        "  }\n"
        "],\n"
        "\"workflow\": [\n"
        "  {\n"
        "    \"step\": 1,\n"
        "    \"description\": \"\",\n"
        "    \"agent\": \"\",\n"
        "    \"input\": \"\",\n"
        "    \"output\": \"\"\n"
        "  }\n"
        "],\n"
        "\"inputs_required\": [],\n"
        "\"expected_outputs\": [],\n"
        "\"tools_required\": [],\n"
        "\"constraints\": [],\n"
        "\"tone\": \"\",\n"
        "\"frequency\": \"\",\n"
        "\"trigger_type\": \"\",\n"
        "\"edge_cases\": [],\n"
        "\"success_criteria\": []\n"
        "}\n\n"
        "---\n\n"
        "EXTRACTION RULES\n\n"
        "### 1. TASK UNDERSTANDING\n\n"
        "* Identify the core goal of the user\n"
        "* Summarize in 1–2 lines → \"task_summary\"\n\n"
        "---\n\n"
        "### 2. INTENT TYPE (choose one)\n\n"
        "* \"automation\"\n"
        "* \"analysis\"\n"
        "* \"generation\"\n"
        "* \"conversation\"\n"
        "* \"multi-step workflow\"\n\n"
        "---\n\n"
        "### 3. COMPLEXITY\n\n"
        "* \"low\" → single step\n"
        "* \"medium\" → 2–4 steps\n"
        "* \"high\" → multi-agent, conditional logic\n\n"
        "---\n\n"
        "### 4. REQUIRED AGENTS\n\n"
        "Infer roles based on task.\n\n"
        "Examples:\n\n"
        "* Email tasks → \"Communication Agent\"\n"
        "* Scheduling → \"Calendar Agent\"\n"
        "* Reports → \"Analysis Agent\"\n"
        "* Education → \"Tutor Agent\"\n"
        "* Finance → \"Finance Assistant\"\n\n"
        "Each agent must have:\n\n"
        "* agent_name\n"
        "* role\n"
        "* responsibilities (array)\n\n"
        "---\n\n"
        "### 5. WORKFLOW GENERATION\n\n"
        "Break the task into ordered steps:\n\n"
        "* Each step must include:\n\n"
        "  * step number\n"
        "  * description\n"
        "  * agent responsible\n"
        "  * input\n"
        "  * output\n\n"
        "---\n\n"
        "### 6. INPUTS REQUIRED\n\n"
        "Extract explicit + implicit inputs:\n"
        "Examples:\n\n"
        "* email address\n"
        "* document\n"
        "* date/time\n"
        "* topic\n"
        "* dataset\n\n"
        "---\n\n"
        "### 7. EXPECTED OUTPUTS\n\n"
        "What should the system produce:\n"
        "Examples:\n\n"
        "* email draft\n"
        "* report summary\n"
        "* schedule\n"
        "* quiz\n"
        "* categorized data\n\n"
        "---\n\n"
        "### 8. TOOLS REQUIRED\n\n"
        "Infer tools/APIs:\n"
        "Examples:\n\n"
        "* email API\n"
        "* calendar API\n"
        "* database\n"
        "* LLM\n"
        "* document parser\n\n"
        "---\n\n"
        "### 9. CONSTRAINTS\n\n"
        "Extract rules like:\n\n"
        "* \"formal tone\"\n"
        "* \"no financial advice\"\n"
        "* \"summarize only\"\n"
        "* \"max 200 words\"\n\n"
        "---\n\n"
        "### 10. TONE\n\n"
        "Examples:\n\n"
        "* formal\n"
        "* professional\n"
        "* friendly\n"
        "* academic\n\n"
        "---\n\n"
        "### 11. FREQUENCY\n\n"
        "If mentioned:\n\n"
        "* one-time\n"
        "* daily\n"
        "* weekly\n"
        "* on-demand\n\n"
        "---\n\n"
        "### 12. TRIGGER TYPE\n\n"
        "* manual\n"
        "* scheduled\n"
        "* event-based\n\n"
        "---\n\n"
        "### 13. EDGE CASES\n\n"
        "Think critically:\n\n"
        "* missing inputs\n"
        "* ambiguous instructions\n"
        "* invalid data\n"
        "* API failure\n\n"
        "---\n\n"
        "### 14. SUCCESS CRITERIA\n\n"
        "Define measurable outcomes:\n\n"
        "* task completed\n"
        "* correct format\n"
        "* no missing fields\n"
        "* user intent satisfied\n\n"
        "---\n\n"
        "DOMAIN-SPECIFIC ADAPTATION\n\n"
        "Use domain knowledge:\n\n"
        "### Corporate Operations\n\n"
        "* Emails, scheduling, reports, internal tools\n\n"
        "### Education\n\n"
        "* Notes, quizzes, explanations, study plans\n\n"
        "### Finance (NON-TRADING ONLY)\n\n"
        "* Expense analysis, summaries, compliance\n"
        "* NEVER include investment advice\n\n"
        "(Refer to domain capabilities accordingly)\n\n"
        "---\n\n"
        "IMPORTANT RULES\n\n"
        "* DO NOT hallucinate unrealistic tools\n\n"
        "* DO NOT include explanations\n\n"
        "* DO NOT return text outside JSON\n\n"
        "* ALWAYS complete all fields (use empty array if needed)\n\n"
        "* Ensure workflow steps are logical and sequential\n\n"
        "* Maintain strict structure for backend parsing\n\n"
        "---\n\n"
        "GOAL\n\n"
        "Convert messy human intent into a clean, structured agent execution plan that can be directly used by a backend orchestration engine.\n"
    )

    payload = {
        "contents": [
            {
                "parts": [
                    {"text": system_instruction},
                    {"text": "\n\nUser prompt:\n" + prompt},
                ]
            }
        ]
    }

    params = {"key": settings.GEMINI_API_KEY}

    async with httpx.AsyncClient(timeout=20.0) as client:
        resp = await client.post(GEMINI_URL, params=params, json=payload)
        resp.raise_for_status()
        data = resp.json()

    # Very basic extraction of first candidate text
    raw_text = (
        data["candidates"][0]["content"]["parts"][0]["text"]
        if data.get("candidates")
        else ""
    )
    return clean_generated_workflow(raw_text)