# app/services/vectorstore.py
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from app.core.config import settings

embeddings = HuggingFaceEmbeddings(model_name=settings.EMBEDDING_MODEL)

vectorstore = FAISS.load_local(
    settings.FAISS_INDEX_PATH,
    embeddings,
    allow_dangerous_deserialization=True  # safe: this index is generated by us, from our own data
)


def search_automations(query: str, category: str | None = None, top_k: int = 5):
    if category:
        results = vectorstore.similarity_search_with_score(query, k=top_k, filter={"category": category})
    else:
        results = vectorstore.similarity_search_with_score(query, k=top_k)
    scored = [
        (doc, float(1 / (1 + distance)))
        for doc, distance in results
    ]
    return scored