"""
OmniAgent — Full Integration Catalog (n8n-sourced, 482 services)

connection_type values:
  - "api_key"      : Pattern 2 — static fields only (API key, tokens, user/pass, etc.)
                      No external registration needed. Connectable immediately for all users.
  - "oauth"         : Pattern 1 — standard OAuth2, n8n needs Client ID + Client Secret.
                      Requires OmniAgent to own a registered OAuth app for this service.
                      Connectable only for services in OAUTH_APPS_REGISTERED (see integration_router.py).
                      Falls back to manual token paste for unregistered services.
  - "oauth_extra"   : Pattern 4 — OAuth2 + additional required static fields (tenant id,
                      subdomain, region, resource name, etc.). Same registration requirement
                      as "oauth", plus the extra fields must be collected in the connect form.
  - "mcp_oauth"      : Pattern 3 — OAuth Redirect URL only, no Client ID/Secret exposed by n8n.
                      Uses MCP's dynamic client registration — no pre-registration needed on
                      OmniAgent's side. Connectable immediately for all users, same as api_key.

Each entry:
{
    "service": "<n8n credential internal key-ish slug>",
    "display_name": "<human label>",
    "category": "<category>",
    "connection_type": "api_key" | "oauth" | "oauth_extra" | "mcp_oauth",
    "fields": [ ... ]  # only for api_key / oauth_extra; empty for pure oauth / mcp_oauth
}

NOTE: `fields` captures the *additional* form fields beyond the OAuth token flow itself
(for oauth_extra) or the full field list (for api_key). Field lists are transcribed from
OmniAgent_Integration_Catalogue.pdf and are intentionally flattened/simplified — some
services have conditional field sets (e.g. "if Password / if Key-pair") which are noted
inline as comments where relevant rather than fully modeled here; refine at connect-form-build time.
"""

INTEGRATION_CATALOG = [
    # ---------------- AI Providers ----------------
    {"service": "openai", "display_name": "OpenAI", "category": "AI Provider", "connection_type": "api_key",
     "fields": ["api_key", "organization_id (optional)", "base_url (default: https://api.openai.com/v1)"]},
    {"service": "anthropic", "display_name": "Anthropic", "category": "AI Provider", "connection_type": "api_key",
     "fields": ["api_key", "base_url (default: https://api.anthropic.com)"]},
    {"service": "groq", "display_name": "Groq", "category": "AI Provider", "connection_type": "api_key",
     "fields": ["api_key"]},
    {"service": "cohere", "display_name": "Cohere", "category": "AI Provider", "connection_type": "api_key",
     "fields": ["api_key"]},
    {"service": "mistral", "display_name": "Mistral Cloud", "category": "AI Provider", "connection_type": "api_key",
     "fields": ["api_key"]},
    {"service": "huggingface", "display_name": "Hugging Face", "category": "AI Provider", "connection_type": "api_key",
     "fields": ["api_key"]},
    {"service": "huggingface_mcp", "display_name": "Hugging Face MCP", "category": "AI Provider", "connection_type": "mcp_oauth", "fields": []},
    {"service": "openrouter", "display_name": "OpenRouter", "category": "AI Provider", "connection_type": "api_key",
     "fields": ["api_key"]},
    {"service": "ollama", "display_name": "Ollama", "category": "AI Provider", "connection_type": "api_key",
     "fields": ["base_url", "api_key"]},
    {"service": "google_gemini", "display_name": "Google Gemini (PaLM)", "category": "AI Provider", "connection_type": "api_key",
     "fields": ["host (default: https://generativelanguage.googleapis.com)", "api_key"]},
    {"service": "azure_openai", "display_name": "Azure OpenAI", "category": "AI Provider", "connection_type": "api_key",
     "fields": ["api_key", "resource_name", "api_version", "endpoint"]},
    {"service": "deepseek", "display_name": "DeepSeek", "category": "AI Provider", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "xai", "display_name": "xAI (Grok)", "category": "AI Provider", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "qwen", "display_name": "Qwen", "category": "AI Provider", "connection_type": "api_key",
     "fields": ["api_key", "region"]},
    {"service": "minimax", "display_name": "MiniMax", "category": "AI Provider", "connection_type": "api_key",
     "fields": ["api_key", "region (International / China)"]},
    {"service": "nvidia_nemotron", "display_name": "NVIDIA Nemotron", "category": "AI Provider", "connection_type": "api_key",
     "fields": ["base_url (default: https://integrate.api.nvidia.com/v1)", "api_key"]},
    {"service": "vercel_ai_gateway", "display_name": "Vercel AI Gateway", "category": "AI Provider", "connection_type": "api_key",
     "fields": ["api_key_or_oidc_token", "base_url (default: https://aigateway.vercel.sh/v1)"]},
    {"service": "google_service_account", "display_name": "Google Service Account", "category": "AI Provider", "connection_type": "api_key",
     "fields": ["region", "service_account_email", "private_key", "impersonate_user (toggle -> email)", "http_request_mode (toggle -> scopes)"]},

    # ---------------- Communication ----------------
    {"service": "gmail", "display_name": "Gmail", "category": "Communication", "connection_type": "oauth", "fields": []},
    {"service": "outlook", "display_name": "Microsoft Outlook", "category": "Communication", "connection_type": "oauth_extra",
     "fields": ["authorization_url", "access_token_url", "graph_api_base_url"]},
    {"service": "smtp_email", "display_name": "SMTP", "category": "Communication", "connection_type": "api_key",
     "fields": ["user", "password", "host", "port", "client_host_name", "ssl_tls", "disable_starttls (if ssl off)"]},
    {"service": "imap", "display_name": "IMAP", "category": "Communication", "connection_type": "api_key",
     "fields": ["user", "password", "host", "port", "ssl_tls", "allow_self_signed_certs"]},
    {"service": "slack", "display_name": "Slack (Access Token)", "category": "Communication", "connection_type": "api_key",
     "fields": ["access_token", "signature_secret"]},
    {"service": "slack_oauth2", "display_name": "Slack OAuth2", "category": "Communication", "connection_type": "oauth_extra",
     "fields": ["signature_secret"]},
    {"service": "microsoft_teams", "display_name": "Microsoft Teams", "category": "Communication", "connection_type": "oauth_extra",
     "fields": ["authorization_url", "access_token_url", "graph_api_base_url"]},
    {"service": "discord_bot", "display_name": "Discord Bot", "category": "Communication", "connection_type": "api_key",
     "fields": ["bot_token"]},
    {"service": "discord_oauth2", "display_name": "Discord OAuth2", "category": "Communication", "connection_type": "oauth_extra",
     "fields": ["authentication_mode (body/header)", "bot_token"]},
    {"service": "discord_webhook", "display_name": "Discord Webhook", "category": "Communication", "connection_type": "api_key",
     "fields": ["webhook_url"]},
    {"service": "telegram", "display_name": "Telegram", "category": "Communication", "connection_type": "api_key",
     "fields": ["access_token", "base_url (default: https://api.telegram.org)"]},
    {"service": "twilio_sms", "display_name": "Twilio", "category": "Communication", "connection_type": "api_key",
     "fields": ["auth_type (token/api_key)", "account_sid", "auth_token_or_api_key_secret"]},
    {"service": "whatsapp", "display_name": "WhatsApp", "category": "Communication", "connection_type": "api_key",
     "fields": ["access_token", "business_account_id"]},
    {"service": "whatsapp_oauth", "display_name": "WhatsApp OAuth", "category": "Communication", "connection_type": "api_key",
     "fields": ["client_id", "client_secret"]},
    {"service": "matrix", "display_name": "Matrix", "category": "Communication", "connection_type": "api_key",
     "fields": ["access_token", "homeserver_url"]},
    {"service": "mattermost", "display_name": "Mattermost", "category": "Communication", "connection_type": "api_key",
     "fields": ["access_token", "base_url", "ignore_ssl_issues"]},
    {"service": "twake", "display_name": "Twake Server", "category": "Communication", "connection_type": "api_key",
     "fields": ["host_url", "public_id", "private_api_key"]},
    {"service": "twist_oauth2", "display_name": "Twist OAuth2", "category": "Communication", "connection_type": "oauth", "fields": []},
    {"service": "signl4", "display_name": "SIGNL4 Webhook", "category": "Communication", "connection_type": "api_key",
     "fields": ["team_secret"]},
    {"service": "gotify", "display_name": "Gotify", "category": "Communication", "connection_type": "api_key",
     "fields": ["app_api_token (optional)", "client_api_token (optional)", "url", "ignore_ssl_issues"]},
    {"service": "pushbullet_oauth2", "display_name": "Pushbullet OAuth2", "category": "Communication", "connection_type": "oauth", "fields": []},
    {"service": "pushcut", "display_name": "Pushcut", "category": "Communication", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "pushover", "display_name": "Pushover", "category": "Communication", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "line_notify_oauth2", "display_name": "Line Notify OAuth2", "category": "Communication", "connection_type": "oauth", "fields": []},
    {"service": "zulip", "display_name": "Zulip", "category": "Communication", "connection_type": "api_key",
     "fields": ["url", "email", "api_key"]},

    # ---------------- Productivity / Calendar / Tasks ----------------
    {"service": "google_calendar", "display_name": "Google Calendar", "category": "Productivity", "connection_type": "oauth", "fields": []},
    {"service": "outlook_calendar", "display_name": "Outlook Calendar", "category": "Productivity", "connection_type": "oauth_extra",
     "fields": ["authorization_url", "access_token_url", "graph_api_base_url"]},
    {"service": "google_contacts", "display_name": "Google Contacts", "category": "Productivity", "connection_type": "oauth", "fields": []},
    {"service": "google_tasks", "display_name": "Google Tasks", "category": "Productivity", "connection_type": "oauth", "fields": []},
    {"service": "microsoft_todo", "display_name": "Microsoft To Do", "category": "Productivity", "connection_type": "oauth_extra",
     "fields": ["authorization_url", "access_token_url", "graph_api_base_url"]},
    {"service": "notion", "display_name": "Notion", "category": "Productivity", "connection_type": "api_key",
     "fields": ["internal_integration_secret"]},
    {"service": "notion_oauth2", "display_name": "Notion OAuth2", "category": "Productivity", "connection_type": "oauth", "fields": []},
    {"service": "notion_mcp", "display_name": "Notion MCP", "category": "Productivity", "connection_type": "mcp_oauth", "fields": []},
    {"service": "trello", "display_name": "Trello", "category": "Productivity", "connection_type": "api_key",
     "fields": ["api_key", "api_token", "oauth_secret"]},
    {"service": "asana", "display_name": "Asana (API)", "category": "Productivity", "connection_type": "api_key",
     "fields": ["access_token"]},
    {"service": "asana_oauth2", "display_name": "Asana OAuth2", "category": "Productivity", "connection_type": "oauth", "fields": []},
    {"service": "clickup", "display_name": "ClickUp (API)", "category": "Productivity", "connection_type": "api_key",
     "fields": ["access_token"]},
    {"service": "clickup_oauth2", "display_name": "ClickUp OAuth2", "category": "Productivity", "connection_type": "oauth", "fields": []},
    {"service": "monday", "display_name": "Monday.com (Token)", "category": "Productivity", "connection_type": "api_key",
     "fields": ["token_v2"]},
    {"service": "monday_oauth2", "display_name": "Monday.com OAuth2", "category": "Productivity", "connection_type": "oauth", "fields": []},
    {"service": "monday_mcp", "display_name": "Monday.com MCP", "category": "Productivity", "connection_type": "mcp_oauth", "fields": []},
    {"service": "todoist", "display_name": "Todoist (API)", "category": "Productivity", "connection_type": "api_key",
     "fields": ["api_key"]},
    {"service": "todoist_oauth2", "display_name": "Todoist OAuth2", "category": "Productivity", "connection_type": "oauth", "fields": []},
    {"service": "toggl", "display_name": "Toggl", "category": "Productivity", "connection_type": "api_key",
     "fields": ["email", "password"]},
    {"service": "clockify", "display_name": "Clockify", "category": "Productivity", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "acuity_scheduling", "display_name": "Acuity Scheduling (API)", "category": "Productivity", "connection_type": "api_key",
     "fields": ["user_id", "api_key"]},
    {"service": "acuity_scheduling_oauth2", "display_name": "Acuity Scheduling OAuth2", "category": "Productivity", "connection_type": "oauth", "fields": []},
    {"service": "calendly_oauth2", "display_name": "Calendly OAuth2", "category": "Productivity", "connection_type": "oauth", "fields": []},
    {"service": "calendly_pat", "display_name": "Calendly (Personal Access Token)", "category": "Productivity", "connection_type": "api_key",
     "fields": ["personal_access_token"]},
    {"service": "orbit", "display_name": "Orbit", "category": "Productivity", "connection_type": "api_key", "fields": ["api_token"]},
    {"service": "wekan", "display_name": "Wekan", "category": "Productivity", "connection_type": "api_key",
     "fields": ["username", "password", "url"]},

    # ---------------- Cloud Storage ----------------
    {"service": "drive", "display_name": "Google Drive", "category": "Cloud Storage", "connection_type": "oauth", "fields": []},
    {"service": "google_cloud_storage", "display_name": "Google Cloud Storage", "category": "Cloud Storage", "connection_type": "oauth", "fields": []},
    {"service": "dropbox", "display_name": "Dropbox (API)", "category": "Cloud Storage", "connection_type": "api_key",
     "fields": ["access_token", "app_access_type (Full Dropbox/App Folder)"]},
    {"service": "dropbox_oauth2", "display_name": "Dropbox OAuth2", "category": "Cloud Storage", "connection_type": "oauth_extra",
     "fields": ["app_access_type (Full Dropbox/App Folder)"]},
    {"service": "onedrive", "display_name": "Microsoft OneDrive", "category": "Cloud Storage", "connection_type": "oauth_extra",
     "fields": ["authorization_url", "access_token_url", "graph_api_base_url"]},
    {"service": "box_oauth2", "display_name": "Box OAuth2", "category": "Cloud Storage", "connection_type": "oauth_extra",
     "fields": ["primary_signature_key (optional)", "secondary_signature_key (optional)"]},
    {"service": "amazon_s3", "display_name": "Amazon S3", "category": "Cloud Storage", "connection_type": "api_key",
     "fields": ["s3_endpoint", "region", "access_key_id", "secret_access_key", "force_path_style", "ignore_ssl_issues"]},
    {"service": "aws_iam", "display_name": "AWS (IAM)", "category": "Cloud Storage", "connection_type": "api_key",
     "fields": ["region", "access_key_id", "secret_access_key"]},
    {"service": "aws_assume_role", "display_name": "AWS (Assume Role)", "category": "Cloud Storage", "connection_type": "api_key",
     "fields": ["region", "sts_access_key_id", "sts_access_key_secret", "sts_session_token (optional)", "role_arn", "external_id", "role_session_name"]},
    {"service": "ftp_sftp", "display_name": "FTP", "category": "Cloud Storage", "connection_type": "api_key",
     "fields": ["host", "port", "username", "password"]},
    {"service": "sftp", "display_name": "SFTP", "category": "Cloud Storage", "connection_type": "api_key",
     "fields": ["host", "port", "username", "password", "private_key", "passphrase"]},
    {"service": "nextcloud", "display_name": "NextCloud (API)", "category": "Cloud Storage", "connection_type": "api_key",
     "fields": ["web_dav_url", "user", "password"]},
    {"service": "nextcloud_oauth2", "display_name": "NextCloud OAuth2", "category": "Cloud Storage", "connection_type": "oauth_extra",
     "fields": ["authorization_url", "access_token_url", "web_dav_url"]},

    # ---------------- Databases ----------------
    {"service": "postgresql", "display_name": "Postgres", "category": "Database", "connection_type": "api_key",
     "fields": ["host", "database", "user", "password", "max_connections", "ignore_ssl_issues"]},
    {"service": "mysql", "display_name": "MySQL", "category": "Database", "connection_type": "api_key",
     "fields": ["host", "database", "user", "password", "port", "connect_timeout"]},
    {"service": "mongodb", "display_name": "MongoDB", "category": "Database", "connection_type": "api_key",
     "fields": ["connection_string_or_host/user/pass", "database", "use_tls (toggle)"]},
    {"service": "redis", "display_name": "Redis", "category": "Database", "connection_type": "api_key",
     "fields": ["password", "user", "host", "port", "database_number"]},
    {"service": "sqlite", "display_name": "SQLite", "category": "Database", "connection_type": "api_key", "fields": ["file_path"]},
    {"service": "supabase", "display_name": "Supabase", "category": "Database", "connection_type": "api_key",
     "fields": ["host", "service_role_secret"]},
    {"service": "airtable_oauth2", "display_name": "Airtable OAuth2", "category": "Database", "connection_type": "oauth", "fields": []},
    {"service": "airtable_pat", "display_name": "Airtable (Personal Access Token)", "category": "Database", "connection_type": "api_key",
     "fields": ["access_token"]},
    {"service": "airtable_mcp", "display_name": "Airtable MCP", "category": "Database", "connection_type": "mcp_oauth", "fields": []},
    {"service": "firebase_firestore", "display_name": "Google Firebase Firestore", "category": "Database", "connection_type": "oauth", "fields": []},
    {"service": "firebase_realtime_db", "display_name": "Google Firebase Realtime Database", "category": "Database", "connection_type": "oauth_extra",
     "fields": ["region"]},
    {"service": "snowflake", "display_name": "Snowflake", "category": "Database", "connection_type": "api_key",
     "fields": ["account", "database", "warehouse", "auth_type (password/key-pair)", "username", "schema", "role"]},
    {"service": "snowflake_oauth2", "display_name": "Snowflake OAuth2", "category": "Database", "connection_type": "oauth_extra",
     "fields": ["account", "database", "warehouse", "schema"]},
    {"service": "microsoft_sql_server", "display_name": "Microsoft SQL Server", "category": "Database", "connection_type": "api_key",
     "fields": ["server", "database", "user", "password", "port", "domain", "tls", "tds_version"]},
    {"service": "oracle_db", "display_name": "Oracle Database", "category": "Database", "connection_type": "api_key",
     "fields": ["user", "password", "connection_string", "privilege"]},
    {"service": "cratedb", "display_name": "CrateDB", "category": "Database", "connection_type": "api_key",
     "fields": ["host", "database", "user", "password", "ssl", "port"]},
    {"service": "questdb", "display_name": "QuestDB", "category": "Database", "connection_type": "api_key",
     "fields": ["host", "database", "user", "password", "ssl", "port"]},
    {"service": "timescaledb", "display_name": "TimescaleDB", "category": "Database", "connection_type": "api_key",
     "fields": ["host", "database", "user", "password", "ignore_ssl_issues", "ssl", "port"]},
    {"service": "databricks", "display_name": "Databricks", "category": "Database", "connection_type": "api_key",
     "fields": ["host", "personal_access_token"]},
    {"service": "databricks_oauth2", "display_name": "Databricks OAuth2", "category": "Database", "connection_type": "oauth_extra",
     "fields": ["host", "token_expired_status_code"]},
    {"service": "microsoft_azure_cosmos_db", "display_name": "Microsoft Azure Cosmos DB", "category": "Database", "connection_type": "api_key",
     "fields": ["account", "key", "database"]},
    {"service": "quick_base", "display_name": "Quick Base", "category": "Database", "connection_type": "api_key",
     "fields": ["hostname", "user_token"]},
    {"service": "nocodb", "display_name": "NocoDB (User Token)", "category": "Database", "connection_type": "api_key",
     "fields": ["user_token", "host"]},
    {"service": "nocodb_api_token", "display_name": "NocoDB (API Token)", "category": "Database", "connection_type": "api_key",
     "fields": ["api_token", "host"]},
    {"service": "grist", "display_name": "Grist", "category": "Database", "connection_type": "api_key",
     "fields": ["api_key", "plan_type"]},
    {"service": "stackby", "display_name": "Stackby", "category": "Database", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "baserow", "display_name": "Baserow (Token)", "category": "Database", "connection_type": "api_key",
     "fields": ["host", "database_token"]},
    {"service": "seatable", "display_name": "SeaTable", "category": "Database", "connection_type": "api_key",
     "fields": ["environment (cloud/self-hosted)", "api_token", "timezone"]},
    {"service": "kobotoolbox", "display_name": "KoBoToolbox (API Token)", "category": "Database", "connection_type": "api_key",
     "fields": ["api_root_url", "api_token"]},

    # ---------------- Documents ----------------
    {"service": "google_docs", "display_name": "Google Docs", "category": "Documents", "connection_type": "oauth", "fields": []},
    {"service": "google_sheets", "display_name": "Google Sheets", "category": "Documents", "connection_type": "oauth", "fields": []},
    {"service": "google_sheets_trigger", "display_name": "Google Sheets Trigger", "category": "Documents", "connection_type": "oauth", "fields": []},
    {"service": "google_slides", "display_name": "Google Slides", "category": "Documents", "connection_type": "oauth", "fields": []},
    {"service": "microsoft_excel_online", "display_name": "Microsoft Excel Online", "category": "Documents", "connection_type": "oauth_extra",
     "fields": ["authorization_url", "access_token_url", "graph_api_base_url"]},
    {"service": "microsoft_word_online", "display_name": "Microsoft SharePoint (Word docs live here)", "category": "Documents", "connection_type": "oauth_extra",
     "fields": ["authorization_url", "access_token_url", "graph_api_base_url", "subdomain"]},
    {"service": "confluence", "display_name": "Confluence", "category": "Documents", "connection_type": "api_key", "fields": []},
    {"service": "gitbook", "display_name": "GitBook", "category": "Documents", "connection_type": "api_key", "fields": []},
    {"service": "contentful", "display_name": "Contentful", "category": "Documents", "connection_type": "api_key",
     "fields": ["space_id", "content_delivery_api_access_token", "content_preview_api_access_token"]},
    {"service": "storyblok_content", "display_name": "Storyblok Content API", "category": "Documents", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "storyblok_management", "display_name": "Storyblok Management API", "category": "Documents", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "coda", "display_name": "Coda", "category": "Documents", "connection_type": "api_key", "fields": ["access_token"]},

    # ---------------- Developer Tools ----------------
    {"service": "github", "display_name": "GitHub (API)", "category": "Developer Tools", "connection_type": "api_key",
     "fields": ["github_server (default: https://api.github.com)", "user", "access_token"]},
    {"service": "github_app", "display_name": "GitHub App", "category": "Developer Tools", "connection_type": "api_key",
     "fields": ["github_server", "app_id_or_client_id", "installation_id", "private_key"]},
    {"service": "github_oauth2", "display_name": "GitHub OAuth2", "category": "Developer Tools", "connection_type": "oauth_extra",
     "fields": ["github_server"]},
    {"service": "gitlab", "display_name": "GitLab (API)", "category": "Developer Tools", "connection_type": "api_key",
     "fields": ["gitlab_server (default: https://gitlab.com)", "access_token"]},
    {"service": "gitlab_oauth2", "display_name": "GitLab OAuth2", "category": "Developer Tools", "connection_type": "oauth_extra",
     "fields": ["gitlab_server"]},
    {"service": "gitlab_mcp", "display_name": "GitLab MCP", "category": "Developer Tools", "connection_type": "mcp_oauth", "fields": []},
    {"service": "bitbucket", "display_name": "Bitbucket (API)", "category": "Developer Tools", "connection_type": "api_key",
     "fields": ["username", "app_password"]},
    {"service": "bitbucket_access_token", "display_name": "Bitbucket (Access Token)", "category": "Developer Tools", "connection_type": "api_key",
     "fields": ["email", "access_token"]},
    {"service": "jira_cloud", "display_name": "Jira SW Cloud (API)", "category": "Developer Tools", "connection_type": "api_key",
     "fields": ["email", "api_token", "domain"]},
    {"service": "jira_cloud_oauth2", "display_name": "Jira SW Cloud OAuth2", "category": "Developer Tools", "connection_type": "oauth_extra",
     "fields": ["domain"]},
    {"service": "jira_server_pat", "display_name": "Jira SW Server (PAT)", "category": "Developer Tools", "connection_type": "api_key",
     "fields": ["personal_access_token", "domain"]},
    {"service": "jira_server", "display_name": "Jira SW Server", "category": "Developer Tools", "connection_type": "api_key",
     "fields": ["email", "password", "domain"]},
    {"service": "jenkins", "display_name": "Jenkins (API)", "category": "Developer Tools", "connection_type": "api_key",
     "fields": ["jenkins_username", "personal_api_token", "jenkins_instance_url"]},
    {"service": "azure_devops", "display_name": "Azure DevOps", "category": "Developer Tools", "connection_type": "api_key", "fields": []},
    {"service": "docker", "display_name": "Docker", "category": "Developer Tools", "connection_type": "api_key", "fields": []},
    {"service": "npm", "display_name": "Npm", "category": "Developer Tools", "connection_type": "api_key",
     "fields": ["access_token", "registry_url"]},
    {"service": "circleci", "display_name": "CircleCI", "category": "Developer Tools", "connection_type": "api_key",
     "fields": ["personal_api_token"]},
    {"service": "travis_ci", "display_name": "Travis CI", "category": "Developer Tools", "connection_type": "api_key", "fields": ["api_token"]},
    {"service": "netlify", "display_name": "Netlify", "category": "Developer Tools", "connection_type": "api_key", "fields": ["access_token"]},
    {"service": "railway_mcp", "display_name": "Railway MCP", "category": "Developer Tools", "connection_type": "mcp_oauth", "fields": []},
    {"service": "postman_mcp", "display_name": "Postman MCP", "category": "Developer Tools", "connection_type": "mcp_oauth", "fields": []},
    {"service": "cypress_cloud_mcp", "display_name": "Cypress Cloud MCP", "category": "Developer Tools", "connection_type": "mcp_oauth", "fields": []},
    {"service": "prisma_mcp", "display_name": "Prisma MCP", "category": "Developer Tools", "connection_type": "mcp_oauth", "fields": []},

    # ---------------- CRM & Sales ----------------
    {"service": "salesforce_oauth2", "display_name": "Salesforce OAuth2", "category": "CRM", "connection_type": "oauth_extra",
     "fields": ["environment_type (Production/Sandbox)"]},
    {"service": "salesforce_jwt", "display_name": "Salesforce JWT", "category": "CRM", "connection_type": "api_key",
     "fields": ["environment_type", "client_id", "username", "private_key", "my_domain_url"]},
    {"service": "hubspot_oauth2", "display_name": "HubSpot OAuth2", "category": "CRM", "connection_type": "oauth", "fields": []},
    {"service": "hubspot_developer", "display_name": "HubSpot Developer API", "category": "CRM", "connection_type": "oauth_extra",
     "fields": ["developer_api_key", "app_id"]},
    {"service": "hubspot_service_key", "display_name": "HubSpot (Service Key)", "category": "CRM", "connection_type": "api_key",
     "fields": ["service_key"]},
    {"service": "zoho_oauth2", "display_name": "Zoho OAuth2", "category": "CRM", "connection_type": "oauth", "fields": []},
    {"service": "pipedrive_api", "display_name": "Pipedrive (API)", "category": "CRM", "connection_type": "api_key", "fields": ["api_token"]},
    {"service": "pipedrive_oauth2", "display_name": "Pipedrive OAuth2", "category": "CRM", "connection_type": "oauth", "fields": []},
    {"service": "freshsales", "display_name": "Freshworks CRM", "category": "CRM", "connection_type": "api_key",
     "fields": ["api_key", "domain"]},
    {"service": "close_mcp", "display_name": "Close MCP", "category": "CRM", "connection_type": "mcp_oauth", "fields": []},
    {"service": "affinity", "display_name": "Affinity", "category": "CRM", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "agile_crm", "display_name": "AgileCRM", "category": "CRM", "connection_type": "api_key",
     "fields": ["email", "api_key", "subdomain"]},
    {"service": "copper", "display_name": "Copper", "category": "CRM", "connection_type": "api_key", "fields": ["api_key", "email"]},
    {"service": "salesmate", "display_name": "Salesmate", "category": "CRM", "connection_type": "api_key",
     "fields": ["session_token", "url"]},
    {"service": "monica_crm", "display_name": "Monica CRM", "category": "CRM", "connection_type": "api_key",
     "fields": ["environment (cloud/self-hosted)", "api_token"]},
    {"service": "highlevel_api", "display_name": "HighLevel (API)", "category": "CRM", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "highlevel_oauth2", "display_name": "HighLevel OAuth2", "category": "CRM", "connection_type": "oauth_extra",
     "fields": ["authorization_url_variant", "scope"]},
    {"service": "activecampaign", "display_name": "ActiveCampaign", "category": "CRM", "connection_type": "api_key", "fields": ["api_key"]},

    # ---------------- Finance & Payments ----------------
    {"service": "stripe_mcp", "display_name": "Stripe MCP", "category": "Finance", "connection_type": "mcp_oauth", "fields": []},
    {"service": "razorpay", "display_name": "Razorpay", "category": "Finance", "connection_type": "api_key", "fields": []},
    {"service": "paypal_api", "display_name": "PayPal", "category": "Finance", "connection_type": "api_key",
     "fields": ["client_id", "secret", "environment (Live/Sandbox)"]},
    {"service": "paypal_mcp", "display_name": "PayPal MCP", "category": "Finance", "connection_type": "mcp_oauth", "fields": []},
    {"service": "quickbooks_oauth2", "display_name": "QuickBooks Online OAuth2", "category": "Finance", "connection_type": "oauth_extra",
     "fields": ["environment (Live/Sandbox)"]},
    {"service": "xero", "display_name": "Xero", "category": "Finance", "connection_type": "api_key", "fields": []},
    {"service": "wise", "display_name": "Wise", "category": "Finance", "connection_type": "api_key",
     "fields": ["api_token", "environment (Live/Test)", "private_key (optional)"]},
    {"service": "chargebee", "display_name": "Chargebee", "category": "Finance", "connection_type": "api_key",
     "fields": ["account_name", "api_key"]},
    {"service": "paddle", "display_name": "Paddle", "category": "Finance", "connection_type": "api_key",
     "fields": ["vendor_auth_code", "vendor_id", "use_sandbox_environment"]},
    {"service": "profitwell", "display_name": "ProfitWell", "category": "Finance", "connection_type": "api_key", "fields": ["api_token"]},

    # ---------------- Social Media ----------------
    {"service": "x_twitter_oauth2", "display_name": "X (Twitter) OAuth2", "category": "Social Media", "connection_type": "oauth", "fields": []},
    {"service": "linkedin_oauth2", "display_name": "LinkedIn OAuth2", "category": "Social Media", "connection_type": "oauth_extra",
     "fields": ["organization_support (toggle)", "legacy (toggle)"]},
    {"service": "linkedin_community_mgmt_oauth2", "display_name": "LinkedIn Community Management OAuth2", "category": "Social Media", "connection_type": "oauth", "fields": []},
    {"service": "facebook_graph_api", "display_name": "Facebook Graph API", "category": "Social Media", "connection_type": "api_key",
     "fields": ["access_token"]},
    {"service": "facebook_graph_oauth2", "display_name": "Facebook Graph OAuth2", "category": "Social Media", "connection_type": "oauth", "fields": []},
    {"service": "facebook_graph_app_oauth2", "display_name": "Facebook Graph (App) OAuth2", "category": "Social Media", "connection_type": "oauth_extra",
     "fields": ["app_secret"]},
    {"service": "facebook_lead_ads_oauth2", "display_name": "Facebook Lead Ads OAuth2", "category": "Social Media", "connection_type": "oauth", "fields": []},
    {"service": "instagram_business", "display_name": "Instagram Business", "category": "Social Media", "connection_type": "oauth", "fields": []},
    {"service": "youtube", "display_name": "YouTube (via Google OAuth2)", "category": "Social Media", "connection_type": "oauth_extra",
     "fields": ["scope"]},
    {"service": "reddit_oauth2", "display_name": "Reddit OAuth2", "category": "Social Media", "connection_type": "oauth", "fields": []},
    {"service": "pinterest", "display_name": "Pinterest", "category": "Social Media", "connection_type": "oauth", "fields": []},
    {"service": "medium_api", "display_name": "Medium (API)", "category": "Social Media", "connection_type": "api_key", "fields": ["access_token"]},
    {"service": "medium_oauth2", "display_name": "Medium OAuth2", "category": "Social Media", "connection_type": "oauth", "fields": []},

    # ---------------- Forms ----------------
    {"service": "google_forms", "display_name": "Google Forms", "category": "Forms", "connection_type": "oauth", "fields": []},
    {"service": "typeform_api", "display_name": "Typeform (API)", "category": "Forms", "connection_type": "api_key", "fields": ["access_token"]},
    {"service": "typeform_oauth2", "display_name": "Typeform OAuth2", "category": "Forms", "connection_type": "oauth", "fields": []},
    {"service": "jotform", "display_name": "JotForm", "category": "Forms", "connection_type": "api_key",
     "fields": ["api_key", "api_domain"]},
    {"service": "jotform_mcp", "display_name": "Jotform MCP", "category": "Forms", "connection_type": "mcp_oauth", "fields": []},
    {"service": "tally", "display_name": "Tally", "category": "Forms", "connection_type": "api_key", "fields": []},
    {"service": "formstack_api", "display_name": "Formstack (API)", "category": "Forms", "connection_type": "api_key", "fields": ["access_token"]},
    {"service": "formstack_oauth2", "display_name": "Formstack OAuth2", "category": "Forms", "connection_type": "oauth", "fields": []},
    {"service": "wufoo", "display_name": "Wufoo", "category": "Forms", "connection_type": "api_key",
     "fields": ["api_key", "subdomain"]},

    # ---------------- Search & Web ----------------
    {"service": "http", "display_name": "HTTP (Generic)", "category": "Search & Web", "connection_type": "api_key", "fields": []},
    {"service": "graphql", "display_name": "GraphQL (Generic)", "category": "Search & Web", "connection_type": "api_key", "fields": []},
    {"service": "webhook", "display_name": "Webhook (Generic)", "category": "Search & Web", "connection_type": "api_key", "fields": []},
    {"service": "rss_feed", "display_name": "RSS Feed", "category": "Search & Web", "connection_type": "api_key", "fields": []},
    {"service": "serpapi", "display_name": "SerpAPI (via Search & Web)", "category": "Search & Web", "connection_type": "api_key", "fields": []},
    {"service": "tavily", "display_name": "Tavily", "category": "Search & Web", "connection_type": "api_key", "fields": []},
    {"service": "brave_search", "display_name": "Brave Search", "category": "Search & Web", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "google_custom_search", "display_name": "Google Custom Search", "category": "Search & Web", "connection_type": "oauth", "fields": []},
    {"service": "searxng", "display_name": "SearXNG", "category": "Search & Web", "connection_type": "api_key", "fields": ["url"]},
    {"service": "exa_mcp", "display_name": "Exa MCP", "category": "Search & Web", "connection_type": "mcp_oauth", "fields": []},
    {"service": "you_com_mcp", "display_name": "You.com Web Access & AI MCP", "category": "Search & Web", "connection_type": "mcp_oauth", "fields": []},

    # ---------------- Maps & Utilities ----------------
    {"service": "google_maps", "display_name": "Google Maps (via Google OAuth2)", "category": "Utilities", "connection_type": "oauth_extra",
     "fields": ["scope"]},
    {"service": "mapbox_mcp", "display_name": "Mapbox MCP", "category": "Utilities", "connection_type": "mcp_oauth", "fields": []},
    {"service": "openweather", "display_name": "OpenWeatherMap", "category": "Utilities", "connection_type": "api_key", "fields": ["access_token"]},
    {"service": "weatherapi", "display_name": "WeatherAPI", "category": "Utilities", "connection_type": "api_key", "fields": []},
    {"service": "nasa", "display_name": "NASA", "category": "Utilities", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "wolfram_alpha", "display_name": "Wolfram Alpha", "category": "Utilities", "connection_type": "api_key", "fields": ["app_id"]},
    {"service": "yourls", "display_name": "Yourls", "category": "Utilities", "connection_type": "api_key",
     "fields": ["signature", "url"]},
    {"service": "one_simple_api", "display_name": "One Simple API", "category": "Utilities", "connection_type": "api_key", "fields": ["api_token"]},
    {"service": "peekalink", "display_name": "Peekalink", "category": "Utilities", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "totp", "display_name": "TOTP", "category": "Utilities", "connection_type": "api_key",
     "fields": ["secret", "label"]},

    # ---------------- Authentication ----------------
    {"service": "auth0_mgmt", "display_name": "Auth0 Management API", "category": "Authentication", "connection_type": "api_key",
     "fields": ["auth_domain", "client_id", "client_secret"]},
    {"service": "okta_api", "display_name": "Okta (API)", "category": "Authentication", "connection_type": "api_key",
     "fields": ["url", "access_token"]},
    {"service": "azure_entra_id", "display_name": "Azure Entra ID (Azure AD) API", "category": "Authentication", "connection_type": "oauth_extra",
     "fields": ["resource_name", "api_version", "endpoint", "tenant_id (default: common)"]},
    {"service": "microsoft_entra_id", "display_name": "Microsoft Entra ID (Azure AD) API", "category": "Authentication", "connection_type": "oauth_extra",
     "fields": ["graph_api_base_url"]},
    {"service": "microsoft_entra_service_principal", "display_name": "Microsoft Entra Service Principal", "category": "Authentication", "connection_type": "api_key",
     "fields": ["directory_tenant_id", "client_id", "client_secret", "graph_api_base_url"]},
    {"service": "jwt_auth", "display_name": "JWT Auth", "category": "Authentication", "connection_type": "api_key",
     "fields": ["key_type (Passphrase/PEM Key)", "secret_or_keys", "algorithm"]},
    {"service": "basic_auth", "display_name": "Basic Auth", "category": "Authentication", "connection_type": "api_key",
     "fields": ["user", "password"]},
    {"service": "bearer_auth", "display_name": "Bearer Auth", "category": "Authentication", "connection_type": "api_key",
     "fields": ["bearer_token"]},
    {"service": "header_auth", "display_name": "Header Auth", "category": "Authentication", "connection_type": "api_key",
     "fields": ["name", "value"]},
    {"service": "digest_auth", "display_name": "Digest Auth", "category": "Authentication", "connection_type": "api_key",
     "fields": ["user", "password"]},
    {"service": "custom_auth", "display_name": "Custom Auth", "category": "Authentication", "connection_type": "api_key",
     "fields": ["json"]},
    {"service": "ssl_certificates", "display_name": "SSL Certificates", "category": "Authentication", "connection_type": "api_key",
     "fields": ["ca", "certificate", "private_key", "passphrase"]},

    # ---------------- Platform Infrastructure ----------------
    {"service": "n8n_workflow_engine", "display_name": "n8n (API)", "category": "Platform Infrastructure", "connection_type": "api_key",
     "fields": ["api_key", "base_url"]},
    {"service": "faiss_vector_store", "display_name": "FAISS Vector Store", "category": "Platform Infrastructure", "connection_type": "api_key",
     "fields": ["index_path_or_config"]},

    # ---------------- Analytics / Monitoring / Security ----------------
    {"service": "google_analytics_oauth2", "display_name": "Google Analytics OAuth2", "category": "Analytics", "connection_type": "oauth", "fields": []},
    {"service": "google_bigquery_oauth2", "display_name": "Google BigQuery OAuth2", "category": "Analytics", "connection_type": "oauth", "fields": []},
    {"service": "amplitude_mcp", "display_name": "Amplitude MCP", "category": "Analytics", "connection_type": "mcp_oauth", "fields": []},
    {"service": "posthog_api", "display_name": "PostHog (API)", "category": "Analytics", "connection_type": "api_key",
     "fields": ["url", "api_key"]},
    {"service": "posthog_mcp", "display_name": "PostHog MCP", "category": "Analytics", "connection_type": "mcp_oauth", "fields": []},
    {"service": "segment", "display_name": "Segment", "category": "Analytics", "connection_type": "api_key", "fields": ["write_key"]},
    {"service": "mixpanel", "display_name": "Mixpanel", "category": "Analytics", "connection_type": "api_key", "fields": []},
    {"service": "datadog", "display_name": "Datadog (API)", "category": "Analytics", "connection_type": "api_key",
     "fields": ["url", "api_key", "app_key"]},
    {"service": "grafana_api", "display_name": "Grafana (API)", "category": "Analytics", "connection_type": "api_key",
     "fields": ["api_key", "base_url"]},
    {"service": "grafana_mcp", "display_name": "Grafana MCP", "category": "Analytics", "connection_type": "mcp_oauth", "fields": []},
    {"service": "new_relic_mcp", "display_name": "New Relic MCP", "category": "Analytics", "connection_type": "mcp_oauth", "fields": []},
    {"service": "sentry_api_token", "display_name": "Sentry.io (API Token)", "category": "Analytics", "connection_type": "api_key",
     "fields": ["api_token"]},
    {"service": "sentry_oauth2", "display_name": "Sentry.io OAuth2", "category": "Analytics", "connection_type": "oauth", "fields": []},
    {"service": "dynatrace", "display_name": "Dynatrace", "category": "Analytics", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "cloudflare", "display_name": "Cloudflare", "category": "Analytics", "connection_type": "api_key", "fields": ["api_token"]},
    {"service": "gtmetrix_mcp", "display_name": "GTmetrix MCP", "category": "Analytics", "connection_type": "mcp_oauth", "fields": []},
    {"service": "uptime_robot", "display_name": "Uptime Robot", "category": "Analytics", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "solarwinds_observability", "display_name": "SolarWinds Observability", "category": "Analytics", "connection_type": "api_key",
     "fields": ["url", "api_token"]},

    # ---------------- Security ----------------
    {"service": "virustotal", "display_name": "VirusTotal", "category": "Security", "connection_type": "api_key", "fields": ["api_token"]},
    {"service": "urlscan_io", "display_name": "urlscan.io", "category": "Security", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "misp", "display_name": "MISP", "category": "Security", "connection_type": "api_key",
     "fields": ["api_key", "base_url", "allow_unauthorized_certs"]},
    {"service": "the_hive_5", "display_name": "The Hive 5", "category": "Security", "connection_type": "api_key",
     "fields": ["api_key", "url", "ignore_ssl_issues"]},
    {"service": "the_hive", "display_name": "The Hive", "category": "Security", "connection_type": "api_key",
     "fields": ["api_key", "url", "api_version", "ignore_ssl_issues"]},
    {"service": "crowdstrike_oauth2", "display_name": "CrowdStrike OAuth2", "category": "Security", "connection_type": "api_key",
     "fields": ["url", "client_id", "client_secret"]},
    {"service": "cisco_secure_endpoint_amp", "display_name": "Cisco Secure Endpoint (AMP) API", "category": "Security", "connection_type": "api_key",
     "fields": ["region", "client_id", "client_secret"]},
    {"service": "cisco_umbrella", "display_name": "Cisco Umbrella API", "category": "Security", "connection_type": "api_key",
     "fields": ["api_key", "secret"]},
    {"service": "qradar", "display_name": "QRadar", "category": "Security", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "qualys", "display_name": "Qualys", "category": "Security", "connection_type": "api_key",
     "fields": ["username", "password", "requested_with"]},
    {"service": "rapid7_insightvm", "display_name": "Rapid7 InsightVM", "category": "Security", "connection_type": "api_key",
     "fields": ["url", "api_key"]},
    {"service": "alienvault", "display_name": "AlienVault OTX", "category": "Security", "connection_type": "api_key", "fields": ["otx_key"]},
    {"service": "recorded_future", "display_name": "Recorded Future", "category": "Security", "connection_type": "api_key", "fields": ["access_token"]},
    {"service": "dfir_iris", "display_name": "DFIR-IRIS", "category": "Security", "connection_type": "api_key",
     "fields": ["base_url", "api_key", "ignore_ssl"]},
    {"service": "filescan", "display_name": "Filescan", "category": "Security", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "malcore", "display_name": "Malcore", "category": "Security", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "hybrid_analysis", "display_name": "Hybrid Analysis", "category": "Security", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "opencti", "display_name": "OpenCTI", "category": "Security", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "sekoia", "display_name": "Sekoia", "category": "Security", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "elastic_security", "display_name": "Elastic Security", "category": "Security", "connection_type": "api_key",
     "fields": ["base_url", "auth_type (basic/api_key)"]},
    {"service": "trellix_epo", "display_name": "Trellix (McAfee) ePolicy Orchestrator", "category": "Security", "connection_type": "api_key",
     "fields": ["username", "password"]},
    {"service": "imperva_waf", "display_name": "Imperva WAF", "category": "Security", "connection_type": "api_key",
     "fields": ["api_id", "api_key"]},
    {"service": "cisco_meraki", "display_name": "Cisco Meraki", "category": "Security", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "cisco_webex_oauth2", "display_name": "Cisco Webex OAuth2", "category": "Security", "connection_type": "oauth", "fields": []},
    {"service": "f5_bigip", "display_name": "F5 Big-IP", "category": "Security", "connection_type": "api_key",
     "fields": ["username", "password"]},
    {"service": "netscaler_adc", "display_name": "Netscaler ADC", "category": "Security", "connection_type": "api_key",
     "fields": ["url", "username", "password"]},
    {"service": "zscaler_zia", "display_name": "Zscaler ZIA", "category": "Security", "connection_type": "api_key",
     "fields": ["base_url", "username", "password", "api_key"]},
    {"service": "venafi_tls_protect_cloud", "display_name": "Venafi TLS Protect Cloud", "category": "Security", "connection_type": "api_key",
     "fields": ["region", "api_key"]},
    {"service": "venafi_tls_protect_dc", "display_name": "Venafi TLS Protect Datacenter", "category": "Security", "connection_type": "api_key",
     "fields": ["domain", "client_id", "username", "password", "allow_self_signed_certs"]},

    # ---------------- Marketing / Email / CRM-adjacent ----------------
    {"service": "mailchimp_api", "display_name": "Mailchimp (API)", "category": "Marketing", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "mailchimp_oauth2", "display_name": "Mailchimp OAuth2", "category": "Marketing", "connection_type": "oauth", "fields": []},
    {"service": "sendgrid", "display_name": "SendGrid", "category": "Marketing", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "mailgun", "display_name": "Mailgun", "category": "Marketing", "connection_type": "api_key",
     "fields": ["api_domain", "email_domain", "api_key"]},
    {"service": "mailjet_email", "display_name": "Mailjet Email API", "category": "Marketing", "connection_type": "api_key",
     "fields": ["api_key", "secret_key", "sandbox_mode"]},
    {"service": "mailjet_sms", "display_name": "Mailjet SMS", "category": "Marketing", "connection_type": "api_key", "fields": ["token"]},
    {"service": "sendy", "display_name": "Sendy", "category": "Marketing", "connection_type": "api_key",
     "fields": ["url", "api_key"]},
    {"service": "mailerlite", "display_name": "Mailer Lite", "category": "Marketing", "connection_type": "api_key",
     "fields": ["api_key", "classic_api"]},
    {"service": "getresponse_api", "display_name": "GetResponse (API)", "category": "Marketing", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "getresponse_oauth2", "display_name": "GetResponse OAuth2", "category": "Marketing", "connection_type": "oauth", "fields": []},
    {"service": "convertkit", "display_name": "ConvertKit", "category": "Marketing", "connection_type": "api_key", "fields": ["api_secret"]},
    {"service": "customer_io", "display_name": "Customer.io", "category": "Marketing", "connection_type": "api_key",
     "fields": ["tracking_api_key", "region", "tracking_site_id", "app_api_key", "webhook_signing_key"]},
    {"service": "brevo", "display_name": "Brevo", "category": "Marketing", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "iterable", "display_name": "Iterable", "category": "Marketing", "connection_type": "api_key",
     "fields": ["api_key", "region"]},
    {"service": "e_goi", "display_name": "E-Goi", "category": "Marketing", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "vero", "display_name": "Vero", "category": "Marketing", "connection_type": "api_key", "fields": ["auth_token"]},
    {"service": "mandrill", "display_name": "Mandrill", "category": "Marketing", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "mailcheck", "display_name": "Mailcheck", "category": "Marketing", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "dropcontact", "display_name": "Dropcontact", "category": "Marketing", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "lemlist", "display_name": "Lemlist", "category": "Marketing", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "emelia", "display_name": "Emelia", "category": "Marketing", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "autopilot", "display_name": "Autopilot", "category": "Marketing", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "lonescale", "display_name": "LoneScale", "category": "Marketing", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "uplead", "display_name": "Uplead", "category": "Marketing", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "uproc", "display_name": "uProc", "category": "Marketing", "connection_type": "api_key",
     "fields": ["email", "api_key"]},
    {"service": "humantic_ai", "display_name": "Humantic AI", "category": "Marketing", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "hunter", "display_name": "Hunter", "category": "Marketing", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "clearbit", "display_name": "Clearbit", "category": "Marketing", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "brandfetch_api", "display_name": "Brandfetch (API)", "category": "Marketing", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "brandfetch_mcp", "display_name": "Brandfetch MCP", "category": "Marketing", "connection_type": "mcp_oauth", "fields": []},
    {"service": "phantombuster", "display_name": "Phantombuster", "category": "Marketing", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "surveymonkey_api", "display_name": "SurveyMonkey (API)", "category": "Marketing", "connection_type": "api_key",
     "fields": ["access_token", "client_id", "client_secret"]},
    {"service": "surveymonkey_oauth2", "display_name": "SurveyMonkey OAuth2", "category": "Marketing", "connection_type": "oauth", "fields": []},

    # ---------------- E-Commerce ----------------
    {"service": "shopify_access_token", "display_name": "Shopify (Access Token)", "category": "E-Commerce", "connection_type": "api_key",
     "fields": ["shop_subdomain", "access_token", "app_secret_key"]},
    {"service": "shopify_api", "display_name": "Shopify (API)", "category": "E-Commerce", "connection_type": "api_key",
     "fields": ["api_key", "password", "shop_subdomain", "shared_secret"]},
    {"service": "shopify_oauth2", "display_name": "Shopify OAuth2", "category": "E-Commerce", "connection_type": "oauth_extra",
     "fields": ["shop_subdomain"]},
    {"service": "woocommerce", "display_name": "WooCommerce", "category": "E-Commerce", "connection_type": "api_key",
     "fields": ["consumer_key", "consumer_secret", "woocommerce_url", "include_credentials_in_query"]},
    {"service": "magento2", "display_name": "Magento 2", "category": "E-Commerce", "connection_type": "api_key",
     "fields": ["host", "access_token"]},
    {"service": "gumroad_api", "display_name": "Gumroad (API)", "category": "E-Commerce", "connection_type": "api_key", "fields": ["access_token"]},
    {"service": "gumroad_oauth2", "display_name": "Gumroad OAuth2", "category": "E-Commerce", "connection_type": "oauth", "fields": []},
    {"service": "unleashed", "display_name": "Unleashed", "category": "E-Commerce", "connection_type": "api_key",
     "fields": ["api_id", "api_key"]},

    # ---------------- HR / Ops / Misc business tools ----------------
    {"service": "bamboohr", "display_name": "BambooHR", "category": "HR", "connection_type": "api_key",
     "fields": ["subdomain", "api_key"]},
    {"service": "workable", "display_name": "Workable", "category": "HR", "connection_type": "api_key",
     "fields": ["subdomain", "access_token"]},
    {"service": "taiga", "display_name": "Taiga", "category": "HR", "connection_type": "api_key",
     "fields": ["username", "password", "environment"]},
    {"service": "zendesk_api", "display_name": "Zendesk", "category": "HR", "connection_type": "api_key",
     "fields": ["subdomain", "email", "api_token"]},
    {"service": "zendesk_oauth2", "display_name": "Zendesk OAuth2", "category": "HR", "connection_type": "oauth_extra",
     "fields": ["subdomain"]},
    {"service": "freshdesk", "display_name": "Freshdesk", "category": "HR", "connection_type": "api_key",
     "fields": ["api_key", "domain"]},
    {"service": "freshservice", "display_name": "Freshservice", "category": "HR", "connection_type": "api_key",
     "fields": ["api_key", "domain"]},
    {"service": "servicenow_basic", "display_name": "ServiceNow (Basic Auth)", "category": "HR", "connection_type": "api_key",
     "fields": ["user", "password", "subdomain"]},
    {"service": "servicenow_oauth2", "display_name": "ServiceNow OAuth2", "category": "HR", "connection_type": "oauth_extra",
     "fields": ["subdomain"]},
    {"service": "haloPSA", "display_name": "HaloPSA", "category": "HR", "connection_type": "api_key",
     "fields": ["hosting_type", "auth_server_url", "resource_server", "client_id", "client_secret", "tenant"]},
    {"service": "zammad_basic", "display_name": "Zammad (Basic Auth)", "category": "HR", "connection_type": "api_key",
     "fields": ["base_url", "email", "password", "ignore_ssl_issues"]},
    {"service": "zammad_token", "display_name": "Zammad (Token Auth)", "category": "HR", "connection_type": "api_key",
     "fields": ["base_url", "access_token", "ignore_ssl_issues"]},

    # ---------------- Misc / Vertical / Long-tail ----------------
    {"service": "adalo", "display_name": "Adalo", "category": "Utilities", "connection_type": "api_key",
     "fields": ["api_key", "app_id"]},
    {"service": "airtop", "display_name": "Airtop", "category": "Utilities", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "amqp", "display_name": "AMQP", "category": "Utilities", "connection_type": "api_key",
     "fields": ["hostname", "port", "user", "password", "transport_type"]},
    {"service": "apitemplate_io", "display_name": "APITemplate.io", "category": "Utilities", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "azure_ai_search", "display_name": "Azure AI Search", "category": "Utilities", "connection_type": "api_key",
     "fields": ["search_endpoint", "api_key"]},
    {"service": "azure_storage_oauth2", "display_name": "Azure Storage OAuth2", "category": "Utilities", "connection_type": "oauth_extra",
     "fields": ["authorization_url", "access_token_url", "account"]},
    {"service": "azure_storage_shared_key", "display_name": "Azure Storage (Shared Key)", "category": "Utilities", "connection_type": "api_key",
     "fields": ["account", "key"]},
    {"service": "bannerbear", "display_name": "Bannerbear", "category": "Utilities", "connection_type": "api_key", "fields": ["project_api_key"]},
    {"service": "beeminder_api", "display_name": "Beeminder (API)", "category": "Utilities", "connection_type": "api_key", "fields": ["auth_token"]},
    {"service": "beeminder_oauth2", "display_name": "Beeminder OAuth2", "category": "Utilities", "connection_type": "oauth", "fields": []},
    {"service": "bitly_api", "display_name": "Bitly (API)", "category": "Utilities", "connection_type": "api_key", "fields": ["access_token"]},
    {"service": "bitly_oauth2", "display_name": "Bitly OAuth2", "category": "Utilities", "connection_type": "oauth", "fields": []},
    {"service": "bitwarden", "display_name": "Bitwarden", "category": "Utilities", "connection_type": "api_key",
     "fields": ["client_id", "client_secret"]},
    {"service": "bubble", "display_name": "Bubble", "category": "Utilities", "connection_type": "api_key",
     "fields": ["api_token", "app_name", "environment", "hosting"]},
    {"service": "cal_com", "display_name": "Cal.com", "category": "Utilities", "connection_type": "api_key",
     "fields": ["api_key", "host"]},
    {"service": "carbon_black", "display_name": "Carbon Black", "category": "Utilities", "connection_type": "api_key",
     "fields": ["url", "access_token"]},
    {"service": "chromadb_cloud", "display_name": "ChromaDB Cloud", "category": "Utilities", "connection_type": "api_key",
     "fields": ["api_key", "tenant_id", "database_name", "base_url"]},
    {"service": "chromadb_self_hosted", "display_name": "ChromaDB Self-Hosted", "category": "Utilities", "connection_type": "api_key",
     "fields": ["base_url", "authentication (None/API Key/Token)"]},
    {"service": "cockpit", "display_name": "Cockpit", "category": "Utilities", "connection_type": "api_key",
     "fields": ["cockpit_url", "access_token"]},
    {"service": "convertapi", "display_name": "ConvertAPI", "category": "Utilities", "connection_type": "api_key", "fields": ["token"]},
    {"service": "cortex", "display_name": "Cortex", "category": "Utilities", "connection_type": "api_key",
     "fields": ["api_key", "cortex_instance"]},
    {"service": "crypto", "display_name": "Crypto", "category": "Utilities", "connection_type": "api_key",
     "fields": ["hmac_secret", "private_key", "encryption_passphrase", "encryption_public_key", "encryption_private_key"]},
    {"service": "currents", "display_name": "Currents", "category": "Utilities", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "daytona", "display_name": "Daytona", "category": "Utilities", "connection_type": "api_key",
     "fields": ["url", "api_key"]},
    {"service": "deepl", "display_name": "DeepL", "category": "Utilities", "connection_type": "api_key",
     "fields": ["api_key", "api_plan"]},
    {"service": "demio", "display_name": "Demio", "category": "Utilities", "connection_type": "api_key",
     "fields": ["api_key", "api_secret"]},
    {"service": "dhl", "display_name": "DHL", "category": "Utilities", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "discourse", "display_name": "Discourse", "category": "Utilities", "connection_type": "api_key",
     "fields": ["url", "api_key", "username"]},
    {"service": "disqus", "display_name": "Disqus", "category": "Utilities", "connection_type": "api_key", "fields": ["access_token"]},
    {"service": "drift_api", "display_name": "Drift (API)", "category": "Utilities", "connection_type": "api_key", "fields": ["personal_access_token"]},
    {"service": "drift_oauth2", "display_name": "Drift OAuth2", "category": "Utilities", "connection_type": "oauth", "fields": []},
    {"service": "eventbrite_api", "display_name": "Eventbrite (API)", "category": "Utilities", "connection_type": "api_key", "fields": ["private_key"]},
    {"service": "eventbrite_oauth2", "display_name": "Eventbrite OAuth2", "category": "Utilities", "connection_type": "oauth", "fields": []},
    {"service": "erpnext", "display_name": "ERPNext", "category": "Utilities", "connection_type": "api_key",
     "fields": ["api_key", "api_secret", "environment", "subdomain", "domain", "ignore_ssl_issues"]},
    {"service": "figma_api", "display_name": "Figma (API)", "category": "Utilities", "connection_type": "api_key", "fields": ["access_token"]},
    {"service": "figma_oauth2", "display_name": "Figma OAuth2", "category": "Utilities", "connection_type": "oauth_extra",
     "fields": ["auth_uri_query_params (optional)"]},
    {"service": "filemaker", "display_name": "FileMaker", "category": "Utilities", "connection_type": "api_key",
     "fields": ["host", "database", "login", "password"]},
    {"service": "flow", "display_name": "Flow", "category": "Utilities", "connection_type": "api_key",
     "fields": ["organization_id", "access_token"]},
    {"service": "form_io", "display_name": "Form.io", "category": "Utilities", "connection_type": "api_key",
     "fields": ["environment", "email", "password"]},
    {"service": "fortinet_fortigate", "display_name": "Fortinet FortiGate", "category": "Utilities", "connection_type": "api_key", "fields": ["access_token"]},
    {"service": "ghost_admin", "display_name": "Ghost Admin API", "category": "Utilities", "connection_type": "api_key",
     "fields": ["url", "api_key"]},
    {"service": "ghost_content", "display_name": "Ghost Content API", "category": "Utilities", "connection_type": "api_key",
     "fields": ["url", "api_key"]},
    {"service": "git", "display_name": "Git", "category": "Utilities", "connection_type": "api_key",
     "fields": ["username", "password"]},
    {"service": "gong_api", "display_name": "Gong (API)", "category": "Utilities", "connection_type": "api_key",
     "fields": ["base_url", "access_key", "access_key_secret"]},
    {"service": "gong_oauth2", "display_name": "Gong OAuth2", "category": "Utilities", "connection_type": "oauth_extra",
     "fields": ["base_url"]},
    {"service": "google_ads_oauth2", "display_name": "Google Ads OAuth2", "category": "Utilities", "connection_type": "oauth_extra",
     "fields": ["developer_token"]},
    {"service": "google_books_oauth2", "display_name": "Google Books OAuth2", "category": "Utilities", "connection_type": "oauth", "fields": []},
    {"service": "google_business_profile_oauth2", "display_name": "Google Business Profile OAuth2", "category": "Utilities", "connection_type": "oauth", "fields": []},
    {"service": "google_cloud_nl_oauth2", "display_name": "Google Cloud Natural Language OAuth2", "category": "Utilities", "connection_type": "oauth", "fields": []},
    {"service": "google_perspective_oauth2", "display_name": "Google Perspective OAuth2", "category": "Utilities", "connection_type": "oauth", "fields": []},
    {"service": "google_workspace_admin_oauth2", "display_name": "Google Workspace Admin OAuth2", "category": "Utilities", "connection_type": "oauth", "fields": []},
    {"service": "gotowebinar_oauth2", "display_name": "GoToWebinar OAuth2", "category": "Utilities", "connection_type": "oauth", "fields": []},
    {"service": "harvest_api", "display_name": "Harvest (API)", "category": "Utilities", "connection_type": "api_key", "fields": ["access_token"]},
    {"service": "harvest_oauth2", "display_name": "Harvest OAuth2", "category": "Utilities", "connection_type": "oauth", "fields": []},
    {"service": "helpscout_oauth2", "display_name": "HelpScout OAuth2", "category": "Utilities", "connection_type": "oauth", "fields": []},
    {"service": "home_assistant", "display_name": "Home Assistant", "category": "Utilities", "connection_type": "api_key",
     "fields": ["host", "port", "ssl", "access_token"]},
    {"service": "intercom", "display_name": "Intercom", "category": "Utilities", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "invoice_ninja", "display_name": "Invoice Ninja", "category": "Utilities", "connection_type": "api_key",
     "fields": ["url", "api_token", "secret (optional)"]},
    {"service": "jina_ai", "display_name": "Jina AI", "category": "Utilities", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "kafka", "display_name": "Kafka", "category": "Utilities", "connection_type": "api_key",
     "fields": ["client_id", "brokers", "ssl", "authentication"]},
    {"service": "keap_oauth2", "display_name": "Keap OAuth2", "category": "Utilities", "connection_type": "oauth", "fields": []},
    {"service": "kibana", "display_name": "Kibana", "category": "Utilities", "connection_type": "api_key",
     "fields": ["url", "username", "password"]},
    {"service": "ldap", "display_name": "LDAP", "category": "Utilities", "connection_type": "api_key",
     "fields": ["server_address", "port", "binding_dn", "binding_password", "connection_security", "timeout"]},
    {"service": "lemonade", "display_name": "Lemonade", "category": "Utilities", "connection_type": "api_key",
     "fields": ["base_url", "api_key"]},
    {"service": "lingvanex", "display_name": "LingvaNex", "category": "Utilities", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "linear_api", "display_name": "Linear (API)", "category": "Utilities", "connection_type": "api_key",
     "fields": ["api_key", "signing_secret"]},
    {"service": "linear_oauth2", "display_name": "Linear OAuth2", "category": "Utilities", "connection_type": "oauth_extra",
     "fields": ["actor (User/Application)", "include_admin_scope", "signing_secret"]},
    {"service": "matrix_org", "display_name": "Marketstack", "category": "Utilities", "connection_type": "api_key",
     "fields": ["api_key", "use_https"]},
    {"service": "mautic_api", "display_name": "Mautic (API)", "category": "Utilities", "connection_type": "api_key",
     "fields": ["url", "username", "password"]},
    {"service": "mautic_oauth2", "display_name": "Mautic OAuth2", "category": "Utilities", "connection_type": "oauth_extra",
     "fields": ["url"]},
    {"service": "messagebird", "display_name": "MessageBird", "category": "Utilities", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "metabase", "display_name": "Metabase", "category": "Utilities", "connection_type": "api_key",
     "fields": ["url", "username", "password"]},
    {"service": "microsoft_365_agent", "display_name": "Microsoft 365 Agent", "category": "Utilities", "connection_type": "api_key",
     "fields": ["tenant_id", "client_id", "client_secret"]},
    {"service": "microsoft_azure_monitor_oauth2", "display_name": "Microsoft Azure Monitor OAuth2", "category": "Utilities", "connection_type": "oauth_extra",
     "fields": ["tenant_id", "resource", "client_credentials_variant (client_id/client_secret optional)"]},
    {"service": "microsoft_dynamics_oauth2", "display_name": "Microsoft Dynamics OAuth2", "category": "Utilities", "connection_type": "oauth_extra",
     "fields": ["subdomain", "region"]},
    {"service": "microsoft_graph_security_oauth2", "display_name": "Microsoft Graph Security OAuth2", "category": "Utilities", "connection_type": "oauth_extra",
     "fields": ["graph_api_base_url"]},
    {"service": "microsoft_sharepoint_oauth2", "display_name": "Microsoft SharePoint OAuth2", "category": "Utilities", "connection_type": "oauth_extra",
     "fields": ["graph_api_base_url", "subdomain"]},
    {"service": "mist_api", "display_name": "Mist (API)", "category": "Utilities", "connection_type": "api_key",
     "fields": ["api_token", "region"]},
    {"service": "mocean_api", "display_name": "Mocean API", "category": "Utilities", "connection_type": "api_key",
     "fields": ["api_key", "api_secret"]},
    {"service": "milvus", "display_name": "Milvus", "category": "Utilities", "connection_type": "api_key",
     "fields": ["base_url", "username", "password"]},
    {"service": "mindee_invoice", "display_name": "Mindee Invoice API", "category": "Utilities", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "mindee_receipt", "display_name": "Mindee Receipt API", "category": "Utilities", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "miro_oauth2", "display_name": "Miro OAuth2", "category": "Utilities", "connection_type": "oauth", "fields": []},
    {"service": "mqtt", "display_name": "MQTT", "category": "Utilities", "connection_type": "api_key",
     "fields": ["protocol", "host", "port", "username", "password", "clean_session", "client_id"]},
    {"service": "odoo_api", "display_name": "Odoo (API)", "category": "Utilities", "connection_type": "api_key",
     "fields": ["site_url", "username", "password_or_api_key", "database_name"]},
    {"service": "odoo_api_key", "display_name": "Odoo (API Key)", "category": "Utilities", "connection_type": "api_key",
     "fields": ["site_url", "database_name", "api_key"]},
    {"service": "onfleet", "display_name": "Onfleet", "category": "Utilities", "connection_type": "api_key",
     "fields": ["api_key", "signing_secret"]},
    {"service": "oura", "display_name": "Oura", "category": "Utilities", "connection_type": "api_key", "fields": ["personal_access_token"]},
    {"service": "pagerduty_api", "display_name": "PagerDuty (API)", "category": "Utilities", "connection_type": "api_key", "fields": ["api_token"]},
    {"service": "pagerduty_oauth2", "display_name": "PagerDuty OAuth2", "category": "Utilities", "connection_type": "oauth", "fields": []},
    {"service": "philiphue_oauth2", "display_name": "PhilipHue OAuth2", "category": "Utilities", "connection_type": "oauth_extra",
     "fields": ["app_id"]},
    {"service": "pinecone", "display_name": "Pinecone", "category": "Utilities", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "plivo", "display_name": "Plivo", "category": "Utilities", "connection_type": "api_key",
     "fields": ["auth_id", "auth_token"]},
    {"service": "qdrant", "display_name": "Qdrant", "category": "Utilities", "connection_type": "api_key",
     "fields": ["api_key", "qdrant_url"]},
    {"service": "raindrop_oauth2", "display_name": "Raindrop OAuth2", "category": "Utilities", "connection_type": "oauth", "fields": []},
    {"service": "rabbitmq", "display_name": "RabbitMQ", "category": "Utilities", "connection_type": "api_key",
     "fields": ["hostname", "port", "username", "password", "vhost"]},
    {"service": "rocket_api", "display_name": "Rocket (API)", "category": "Utilities", "connection_type": "api_key",
     "fields": ["user_id", "auth_key", "domain"]},
    {"service": "rundeck", "display_name": "Rundeck (API)", "category": "Utilities", "connection_type": "api_key",
     "fields": ["url", "token"]},
    {"service": "schema_registry", "display_name": "Schema Registry", "category": "Utilities", "connection_type": "api_key",
     "fields": ["url", "authentication"]},
    {"service": "sendgrid_mcp", "display_name": "SendPulse MCP", "category": "Utilities", "connection_type": "mcp_oauth", "fields": []},
    {"service": "shuffler", "display_name": "Shuffler", "category": "Utilities", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "spotify_oauth2", "display_name": "Spotify OAuth2", "category": "Utilities", "connection_type": "oauth", "fields": []},
    {"service": "ssh_password", "display_name": "SSH (Password)", "category": "Utilities", "connection_type": "api_key",
     "fields": ["host", "port", "username", "password"]},
    {"service": "ssh_private_key", "display_name": "SSH (Private Key)", "category": "Utilities", "connection_type": "api_key",
     "fields": ["host", "port", "username", "private_key", "passphrase"]},
    {"service": "strapi_api", "display_name": "Strapi (API)", "category": "Utilities", "connection_type": "api_key",
     "fields": ["email", "password", "url", "api_version"]},
    {"service": "strapi_api_token", "display_name": "Strapi API Token", "category": "Utilities", "connection_type": "api_key",
     "fields": ["api_token", "url", "api_version"]},
    {"service": "syncromsp", "display_name": "SyncroMSP", "category": "Utilities", "connection_type": "api_key",
     "fields": ["api_key", "subdomain"]},
    {"service": "sysdig", "display_name": "Sysdig", "category": "Utilities", "connection_type": "api_key", "fields": ["access_token"]},
    {"service": "tapfiliate", "display_name": "Tapfiliate", "category": "Utilities", "connection_type": "api_key", "fields": ["api_key"]},
    {"service": "vertica", "display_name": "Vertica", "category": "Utilities", "connection_type": "api_key",
     "fields": ["url", "username", "password"]},
    {"service": "vonage", "display_name": "Vonage", "category": "Utilities", "connection_type": "api_key",
     "fields": ["api_key", "api_secret"]},
    {"service": "webflow_api", "display_name": "Webflow (API)", "category": "Utilities", "connection_type": "api_key", "fields": ["access_token"]},
    {"service": "webflow_oauth2", "display_name": "Webflow OAuth2", "category": "Utilities", "connection_type": "oauth_extra",
     "fields": ["legacy (toggle)"]},
    {"service": "wordpress_api", "display_name": "Wordpress (API)", "category": "Utilities", "connection_type": "api_key",
     "fields": ["username", "password", "wordpress_url", "ignore_ssl_issues"]},
    {"service": "wordpress_oauth2", "display_name": "WordPress OAuth2", "category": "Utilities", "connection_type": "oauth_extra",
     "fields": ["wordpress_com_site"]},
    {"service": "zabbix", "display_name": "Zabbix (API)", "category": "Utilities", "connection_type": "api_key",
     "fields": ["url", "api_token"]},
    {"service": "zep_api", "display_name": "Zep API", "category": "Utilities", "connection_type": "api_key",
     "fields": ["api_key", "cloud (toggle -> api_url if off)"]},
    {"service": "zoom_oauth2", "display_name": "Zoom OAuth2", "category": "Utilities", "connection_type": "oauth", "fields": []},

    # ---------------- MCP OAuth (redirect-URL-only, dynamic client registration) ----------------
    {"service": "alchemy_mcp", "display_name": "Alchemy MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "altmetric_mcp", "display_name": "Altmetric MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "apify_mcp", "display_name": "Apify MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "atlassian_mcp", "display_name": "Atlassian MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "avo_mcp", "display_name": "Avo MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "axiom_mcp", "display_name": "Axiom MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "bitrix24_mcp", "display_name": "Bitrix24 MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "cdata_connect_ai_mcp", "display_name": "CData Connect AI MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "cello_mcp", "display_name": "Cello MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "composio_mcp", "display_name": "Composio MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "cryptoquant_mcp", "display_name": "CryptoQuant MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "egnyte_remote_mcp", "display_name": "Egnyte Remote MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "fibery_mcp", "display_name": "Fibery MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "fingerprint_mcp", "display_name": "Fingerprint MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "flux_mcp", "display_name": "FLUX MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "guru_remote_mcp", "display_name": "Guru Remote MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "hackle_mcp", "display_name": "Hackle MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "himalayas_remote_jobs_mcp", "display_name": "Himalayas Remote Jobs MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "honeycomb_mcp", "display_name": "Honeycomb MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "ivisa_mcp", "display_name": "Ivisa MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "jumpcloud_mcp", "display_name": "Jumpcloud MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "kajabi_mcp", "display_name": "Kajabi MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "lucid_mcp", "display_name": "Lucid MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "lusha_mcp", "display_name": "Lusha MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "onlyoffice_mcp", "display_name": "Onlyoffice MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "open_video_mcp", "display_name": "Open Video MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "openagenda_mcp", "display_name": "OpenAgenda MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "opusclip_mcp", "display_name": "OpusClip MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "quicknode_mcp", "display_name": "Quicknode MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "rackspace_spot_mcp", "display_name": "Rackspace Spot MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "roboflow_mcp", "display_name": "Roboflow (Official) MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "sanity_mcp", "display_name": "Sanity MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "serpstat_mcp", "display_name": "Serpstat MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "smartbear_mcp", "display_name": "SmartBear MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "snitcher_mcp", "display_name": "Snitcher MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "tenderly_mcp", "display_name": "Tenderly MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "tolstoy_library_mcp", "display_name": "Tolstoy Library MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "unstoppable_domains_mcp", "display_name": "Unstoppable Domains MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "userguiding_mcp", "display_name": "UserGuiding MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "veed_ai_video_generator_mcp", "display_name": "VEED AI Video Generator MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "wix_mcp", "display_name": "Wix MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "wordlift_mcp", "display_name": "Wordlift MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
    {"service": "zigpoll_mcp", "display_name": "Zigpoll MCP", "category": "Platform Infrastructure", "connection_type": "mcp_oauth", "fields": []},
]

# ---------------- Lookup dict (service -> catalog entry) ----------------
# Used by integration_service.py (upsert_integration, etc.) for O(1) lookup
# by service key instead of scanning the full list.
CATALOG_BY_SERVICE = {entry["service"]: entry for entry in INTEGRATION_CATALOG}

# ---------------- OAuth apps OmniAgent has actually registered ----------------
# Only services in this set can use the "Connect with X" flow (Case 2 — OmniAgent-owned
# OAuth app, refresh_token injected into n8n at connect time, per Problem 5).
# Every other "oauth"/"oauth_extra" service in the catalog still shows up in the UI and
# is still usable — it just falls back to manual token paste until registered here.
# Empty/placeholder for now; populate as each app is registered in its dev console.
OAUTH_APPS_REGISTERED: set[str] = {
    "gmail",
    "google_calendar",
    "google_contacts",
    "google_tasks",
    "drive",
    "google_docs",
    "google_sheets",
    "google_sheets_trigger",
    "google_slides",
    # add e.g. "slack_oauth2", "hubspot_oauth2", "github_oauth2", "notion_oauth2"
    # as each is registered in its respective developer console
}


def is_oauth_connect_available(service: str) -> bool:
    """True if this service can use the in-app 'Connect with X' OAuth flow.
    False means either it's not an OAuth service at all, or it is one but
    OmniAgent hasn't registered an app for it yet (falls back to manual token paste)."""
    entry = CATALOG_BY_SERVICE.get(service)
    if not entry or entry["connection_type"] not in ("oauth", "oauth_extra"):
        return False
    return service in OAUTH_APPS_REGISTERED


# ---------------- Summary stats ----------------
if __name__ == "__main__":
    from collections import Counter
    total = len(INTEGRATION_CATALOG)
    by_type = Counter(e["connection_type"] for e in INTEGRATION_CATALOG)
    by_cat = Counter(e["category"] for e in INTEGRATION_CATALOG)
    # print(f"Total catalog entries: {total}")
    # print("By connection_type:", dict(by_type))
    # print("By category:", dict(by_cat))