INTEGRATION_CATALOG = [
    # AI / LLM Providers — split per-provider so a user can connect several at once.
    {"service": "openai", "display_name": "OpenAI", "category": "AI Provider",
     "description": "GPT models for agent reasoning", "fields": ["api_key"]},
    {"service": "anthropic", "display_name": "Anthropic Claude", "category": "AI Provider",
     "description": "Claude models for agent reasoning", "fields": ["api_key"]},
    {"service": "gemini", "display_name": "Google Gemini", "category": "AI Provider",
     "description": "Gemini models for agent reasoning", "fields": ["api_key"]},
    {"service": "groq", "display_name": "Groq", "category": "AI Provider",
     "description": "Groq-hosted models for agent reasoning", "fields": ["api_key"]},
    {"service": "cohere", "display_name": "Cohere", "category": "AI Provider",
     "description": "Cohere models for agent reasoning", "fields": ["api_key"]},
    {"service": "mistral", "display_name": "Mistral AI", "category": "AI Provider",
     "description": "Mistral models for agent reasoning", "fields": ["api_key"]},
    {"service": "huggingface", "display_name": "Hugging Face", "category": "AI Provider",
     "description": "Hosted or Inference API models", "fields": ["api_key"]},
    {"service": "openrouter", "display_name": "OpenRouter", "category": "AI Provider",
     "description": "Unified access to multiple model providers", "fields": ["api_key"]},
    {"service": "ollama", "display_name": "Ollama (Local)", "category": "AI Provider",
     "description": "Locally hosted open models", "fields": ["base_url"]},

    # Communication
    {"service": "gmail", "display_name": "Gmail", "category": "Communication",
     "description": "Send and read emails", "fields": ["client_id", "client_secret", "refresh_token"]},
    {"service": "outlook", "display_name": "Microsoft Outlook", "category": "Communication",
     "description": "Send and read emails via Outlook", "fields": ["client_id", "client_secret", "refresh_token"]},
    {"service": "smtp_email", "display_name": "SMTP Email", "category": "Communication",
     "description": "Send email via a raw SMTP server", "fields": ["host", "port", "username", "password"]},
    {"service": "slack", "display_name": "Slack", "category": "Communication",
     "description": "Deploy agents in team channels", "fields": ["bot_token"]},
    {"service": "microsoft_teams", "display_name": "Microsoft Teams", "category": "Communication",
     "description": "Post messages in Teams channels", "fields": ["client_id", "client_secret", "refresh_token"]},
    {"service": "discord", "display_name": "Discord", "category": "Communication",
     "description": "Deploy agents in Discord servers", "fields": ["bot_token"]},
    {"service": "telegram", "display_name": "Telegram", "category": "Communication",
     "description": "Send/receive Telegram bot messages", "fields": ["bot_token"]},
    {"service": "twilio_sms", "display_name": "Twilio SMS", "category": "Communication",
     "description": "Send SMS messages via Twilio", "fields": ["account_sid", "auth_token", "from_number"]},
    {"service": "whatsapp", "display_name": "WhatsApp Cloud API", "category": "Communication",
     "description": "Send WhatsApp messages via Meta's Business API", "fields": ["access_token", "phone_number_id"]},

    # Productivity
    {"service": "google_calendar", "display_name": "Google Calendar", "category": "Productivity",
     "description": "Schedule meetings and manage availability", "fields": ["client_id", "client_secret", "refresh_token"]},
    {"service": "outlook_calendar", "display_name": "Outlook Calendar", "category": "Productivity",
     "description": "Schedule meetings via Microsoft Calendar", "fields": ["client_id", "client_secret", "refresh_token"]},
    {"service": "google_contacts", "display_name": "Google Contacts", "category": "Productivity",
     "description": "Read and manage contacts", "fields": ["client_id", "client_secret", "refresh_token"]},
    {"service": "google_tasks", "display_name": "Google Tasks", "category": "Productivity",
     "description": "Manage task lists", "fields": ["client_id", "client_secret", "refresh_token"]},
    {"service": "notion", "display_name": "Notion", "category": "Productivity",
     "description": "Index knowledge bases and documents", "fields": ["api_key"]},
    {"service": "trello", "display_name": "Trello", "category": "Productivity",
     "description": "Manage boards, lists, and cards", "fields": ["api_key", "token"]},
    {"service": "asana", "display_name": "Asana", "category": "Productivity",
     "description": "Manage tasks and projects", "fields": ["access_token"]},
    {"service": "clickup", "display_name": "ClickUp", "category": "Productivity",
     "description": "Manage tasks and workflows", "fields": ["api_key"]},
    {"service": "monday", "display_name": "Monday.com", "category": "Productivity",
     "description": "Manage boards and items", "fields": ["api_key"]},
    {"service": "todoist", "display_name": "Todoist", "category": "Productivity",
     "description": "Manage personal task lists", "fields": ["api_key"]},

    # Cloud Storage
    {"service": "drive", "display_name": "Google Drive", "category": "Cloud Storage",
     "description": "Access and manage files in Drive", "fields": ["client_id", "client_secret", "refresh_token"]},
    {"service": "dropbox", "display_name": "Dropbox", "category": "Cloud Storage",
     "description": "Access and manage files in Dropbox", "fields": ["access_token"]},
    {"service": "onedrive", "display_name": "OneDrive", "category": "Cloud Storage",
     "description": "Access and manage files in OneDrive", "fields": ["client_id", "client_secret", "refresh_token"]},
    {"service": "box", "display_name": "Box", "category": "Cloud Storage",
     "description": "Access and manage files in Box", "fields": ["client_id", "client_secret", "refresh_token"]},
    {"service": "amazon_s3", "display_name": "Amazon S3", "category": "Cloud Storage",
     "description": "Store and retrieve files in S3", "fields": ["access_key", "secret_key", "bucket_name", "region"]},
    {"service": "ftp_sftp", "display_name": "FTP / SFTP", "category": "Cloud Storage",
     "description": "Transfer files over FTP/SFTP", "fields": ["host", "port", "username", "password"]},

    # Databases
    {"service": "postgresql", "display_name": "PostgreSQL", "category": "Database",
     "description": "Query and update a PostgreSQL database", "fields": ["connection_string"]},
    {"service": "mysql", "display_name": "MySQL", "category": "Database",
     "description": "Query and update a MySQL database", "fields": ["connection_string"]},
    {"service": "mongodb", "display_name": "MongoDB", "category": "Database",
     "description": "Query and update a MongoDB database", "fields": ["connection_string"]},
    {"service": "redis", "display_name": "Redis", "category": "Database",
     "description": "Read/write a Redis instance", "fields": ["connection_string"]},
    {"service": "sqlite", "display_name": "SQLite", "category": "Database",
     "description": "Query a SQLite file", "fields": ["file_path"]},
    {"service": "supabase", "display_name": "Supabase", "category": "Database",
     "description": "Query a Supabase project", "fields": ["project_url", "api_key"]},
    {"service": "airtable", "display_name": "Airtable", "category": "Database",
     "description": "Read and write Airtable bases", "fields": ["api_key", "base_id"]},
    {"service": "firebase", "display_name": "Firebase Firestore", "category": "Database",
     "description": "Query and update Firestore", "fields": ["project_id", "service_account_json"]},

    # Documents
    {"service": "google_docs", "display_name": "Google Docs", "category": "Documents",
     "description": "Create and edit documents", "fields": ["client_id", "client_secret", "refresh_token"]},
    {"service": "google_sheets", "display_name": "Google Sheets", "category": "Documents",
     "description": "Read and write spreadsheet data", "fields": ["client_id", "client_secret", "refresh_token"]},
    {"service": "microsoft_excel_online", "display_name": "Microsoft Excel Online", "category": "Documents",
     "description": "Read and write Excel spreadsheets", "fields": ["client_id", "client_secret", "refresh_token"]},
    {"service": "microsoft_word_online", "display_name": "Microsoft Word Online", "category": "Documents",
     "description": "Create and edit Word documents", "fields": ["client_id", "client_secret", "refresh_token"]},
    {"service": "confluence", "display_name": "Confluence", "category": "Documents",
     "description": "Manage Confluence pages", "fields": ["domain", "email", "api_token"]},
    {"service": "gitbook", "display_name": "GitBook", "category": "Documents",
     "description": "Manage GitBook content", "fields": ["api_key"]},

    # Developer Tools
    {"service": "github", "display_name": "GitHub", "category": "Developer Tools",
     "description": "Manage repos, issues, and pull requests", "fields": ["access_token"]},
    {"service": "gitlab", "display_name": "GitLab", "category": "Developer Tools",
     "description": "Manage repos, issues, and merge requests", "fields": ["access_token"]},
    {"service": "bitbucket", "display_name": "Bitbucket", "category": "Developer Tools",
     "description": "Manage repos and pull requests", "fields": ["username", "app_password"]},
    {"service": "jira", "display_name": "Jira", "category": "Developer Tools",
     "description": "Manage issues and sprints", "fields": ["domain", "email", "api_token"]},
    {"service": "jenkins", "display_name": "Jenkins", "category": "Developer Tools",
     "description": "Trigger and monitor CI jobs", "fields": ["base_url", "username", "api_token"]},
    {"service": "azure_devops", "display_name": "Azure DevOps", "category": "Developer Tools",
     "description": "Manage boards and pipelines", "fields": ["organization", "personal_access_token"]},
    {"service": "docker", "display_name": "Docker", "category": "Developer Tools",
     "description": "Push/pull images via a registry", "fields": ["registry_url", "username", "password"]},

    # CRM & Sales
    {"service": "salesforce", "display_name": "Salesforce", "category": "CRM",
     "description": "Manage leads, contacts, and opportunities", "fields": ["client_id", "client_secret", "refresh_token", "instance_url"]},
    {"service": "hubspot", "display_name": "HubSpot", "category": "CRM",
     "description": "Manage contacts, deals, and pipelines", "fields": ["api_key"]},
    {"service": "zoho_crm", "display_name": "Zoho CRM", "category": "CRM",
     "description": "Manage leads and deals", "fields": ["client_id", "client_secret", "refresh_token"]},
    {"service": "pipedrive", "display_name": "Pipedrive", "category": "CRM",
     "description": "Manage sales pipelines and deals", "fields": ["api_key"]},
    {"service": "freshsales", "display_name": "Freshsales", "category": "CRM",
     "description": "Manage leads and contacts", "fields": ["domain", "api_key"]},

    # Finance & Payments
    {"service": "stripe", "display_name": "Stripe", "category": "Finance",
     "description": "Process payments and subscriptions", "fields": ["secret_key"]},
    {"service": "razorpay", "display_name": "Razorpay", "category": "Finance",
     "description": "Process payments", "fields": ["key_id", "key_secret"]},
    {"service": "paypal", "display_name": "PayPal", "category": "Finance",
     "description": "Process payments via PayPal", "fields": ["client_id", "client_secret"]},
    {"service": "quickbooks", "display_name": "QuickBooks", "category": "Finance",
     "description": "Manage invoices and accounting records", "fields": ["client_id", "client_secret", "refresh_token", "realm_id"]},
    {"service": "xero", "display_name": "Xero", "category": "Finance",
     "description": "Manage invoices and accounting records", "fields": ["client_id", "client_secret", "refresh_token"]},

    # Social Media
    {"service": "x_twitter", "display_name": "X (Twitter)", "category": "Social Media",
     "description": "Post and read tweets", "fields": ["api_key", "api_secret", "access_token", "access_token_secret"]},
    {"service": "linkedin", "display_name": "LinkedIn", "category": "Social Media",
     "description": "Post and manage LinkedIn content", "fields": ["client_id", "client_secret", "access_token"]},
    {"service": "facebook", "display_name": "Facebook", "category": "Social Media",
     "description": "Manage Facebook Page posts", "fields": ["access_token", "page_id"]},
    {"service": "instagram_business", "display_name": "Instagram Business", "category": "Social Media",
     "description": "Manage Instagram Business content", "fields": ["access_token", "ig_user_id"]},
    {"service": "youtube", "display_name": "YouTube", "category": "Social Media",
     "description": "Manage videos and channel data", "fields": ["client_id", "client_secret", "refresh_token"]},
    {"service": "reddit", "display_name": "Reddit", "category": "Social Media",
     "description": "Post and read Reddit content", "fields": ["client_id", "client_secret", "username", "password"]},
    {"service": "pinterest", "display_name": "Pinterest", "category": "Social Media",
     "description": "Manage Pinterest pins and boards", "fields": ["access_token"]},

    # Forms
    {"service": "google_forms", "display_name": "Google Forms", "category": "Forms",
     "description": "Collect form responses", "fields": ["client_id", "client_secret", "refresh_token"]},
    {"service": "typeform", "display_name": "Typeform", "category": "Forms",
     "description": "Collect form responses", "fields": ["api_key"]},
    {"service": "jotform", "display_name": "JotForm", "category": "Forms",
     "description": "Collect form responses", "fields": ["api_key"]},
    {"service": "tally", "display_name": "Tally", "category": "Forms",
     "description": "Collect form responses", "fields": ["api_key"]},
    {"service": "formstack", "display_name": "Formstack", "category": "Forms",
     "description": "Collect form responses", "fields": ["api_key"]},

    # Search & Web
    {"service": "http", "display_name": "Generic HTTP", "category": "Search & Web",
     "description": "Call an arbitrary REST endpoint", "fields": ["base_url", "api_key"]},
    {"service": "graphql", "display_name": "GraphQL", "category": "Search & Web",
     "description": "Query a GraphQL endpoint", "fields": ["endpoint_url", "api_key"]},
    {"service": "webhook", "display_name": "Webhook", "category": "Search & Web",
     "description": "Receive events via webhook", "fields": ["webhook_secret"]},
    {"service": "rss_feed", "display_name": "RSS Feed", "category": "Search & Web",
     "description": "Poll an RSS/Atom feed", "fields": ["feed_url"]},
    {"service": "serpapi", "display_name": "SerpAPI", "category": "Search & Web",
     "description": "Search engine results API", "fields": ["api_key"]},
    {"service": "tavily", "display_name": "Tavily", "category": "Search & Web",
     "description": "AI-focused web search API", "fields": ["api_key"]},
    {"service": "brave_search", "display_name": "Brave Search", "category": "Search & Web",
     "description": "Brave's search API", "fields": ["api_key"]},
    {"service": "google_custom_search", "display_name": "Google Custom Search", "category": "Search & Web",
     "description": "Google's Programmable Search API", "fields": ["api_key", "cx_id"]},

    # Maps & Utilities
    {"service": "google_maps", "display_name": "Google Maps", "category": "Utilities",
     "description": "Geocoding, directions, places", "fields": ["api_key"]},
    {"service": "mapbox", "display_name": "Mapbox", "category": "Utilities",
     "description": "Maps and geocoding", "fields": ["access_token"]},
    {"service": "openweather", "display_name": "OpenWeather", "category": "Utilities",
     "description": "Weather data API", "fields": ["api_key"]},
    {"service": "weatherapi", "display_name": "WeatherAPI", "category": "Utilities",
     "description": "Weather data API", "fields": ["api_key"]},

    # Authentication
    {"service": "auth0", "display_name": "Auth0", "category": "Authentication",
     "description": "Manage users via Auth0", "fields": ["domain", "client_id", "client_secret"]},
    {"service": "clerk", "display_name": "Clerk", "category": "Authentication",
     "description": "Manage users via Clerk", "fields": ["api_key"]},
    {"service": "firebase_authentication", "display_name": "Firebase Authentication", "category": "Authentication",
     "description": "Manage users via Firebase Auth", "fields": ["project_id", "service_account_json"]},
    {"service": "keycloak", "display_name": "Keycloak", "category": "Authentication",
     "description": "Manage users via Keycloak", "fields": ["base_url", "realm", "client_id", "client_secret"]},
    {"service": "okta", "display_name": "Okta", "category": "Authentication",
     "description": "Manage users via Okta", "fields": ["domain", "api_token"]},

    # Platform Infrastructure — credential storage only; runtime routing not implemented yet.
    {"service": "faiss_vector_store", "display_name": "FAISS Vector Store", "category": "Platform Infrastructure",
     "description": "Point automation embeddings at your own vector store", "fields": ["endpoint_url"]},
    {"service": "n8n_workflow_engine", "display_name": "n8n Workflow Engine", "category": "Platform Infrastructure",
     "description": "Deploy generated workflows to your own n8n instance", "fields": ["base_url", "api_key"]},
]

CATALOG_BY_SERVICE = {item["service"]: item for item in INTEGRATION_CATALOG}